
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git
         zsh-autosuggestions
         zsh-syntax-highlighting
         starship)

source $ZSH/oh-my-zsh.sh

alias m='micro'
alias ls='lsd'
alias l='ls --tree'
alias cd='z'
alias x='clear'
alias v='nvim'
alias sharingan='home-manager switch'
alias rene-sharingan='nvim ~/.config/home-manager/home.nix'
alias lt='ls --tree'
alias c='cd'
alias q='cd ..'
alias yay='pacstall'
alias dot='cd ~/pista/dotfiles/'
alias gh='github-desktop'


eval "$(zoxide init zsh)"
eval "$(starship init zsh)"

export TERM="xterm-256color"


# for strtup terminal command 
# you can edit this for your pefernce ! 
#nitch

# for transient prompt with starship or other prompt !! 
# then remove the hash if you want t-prompt then only . 
# uncomment this line on your favor for development ! 
# bye linux dev !

zle-line-init() {
  emulate -L zsh
  [[ $CONTEXT == start ]] || return 0
  while true; do
    zle .recursive-edit
    local -i ret=$?
    [[ $ret == 0 && $KEYS == $'\4' ]] || break
    [[ -o ignore_eof ]] || exit 0
  done
  local saved_prompt=$PROMPT
  local saved_rprompt=$RPROMPT
  PROMPT='$(STARSHIP_CONFIG=~/.config/starship/config-transient.toml starship prompt --terminal-width="$COLUMNS" --keymap="${KEYMAP:-}" --status="$STARSHIP_CMD_STATUS" --pipestatus="${STARSHIP_PIPE_STATUS[*]}" --cmd-duration="${STARSHIP_DURATION:-}" --jobs="$STARSHIP_JOBS_COUNT")'
  RPROMPT=''
  zle .reset-prompt
  PROMPT=$saved_prompt
  RPROMPT=$saved_rprompt
  if (( ret )); then
    zle .send-break
 else
    zle .accept-line
  fi
  return ret
}
zle -N zle-line-init
