# ~/.config/starship.toml

# Optional: Show a blank line between prompts
add_newline = true

# The main prompt format (two lines with your custom characters)
# ~/.config/starship.toml

format = """\
[╭─ $directory](bold cyan)
[╰─❯](bold green) """



# Optional: Custom 'character' module if you want colors or change symbol on success/error
[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[directory]
truncation_length = 0         # Show full path without truncation
style = "cyan bold"           # Color and style of directory
read_only = " (RO)"           # Optional suffix if directory is read-only

